import { describe, it, expect, vi, afterEach } from 'vitest'
import worker from '../worker'

// Generated by gen-worker-test.js, then adapted to this worker's 302
// bare-path-redirect style (pooldose pattern) and extended with the
// /api/wbgt NWS proxy cases.

// Return a fresh Response per call — sharing a single instance causes "body
// locked" errors when the worker consumes the body via new Response(res.body).
function okFetch() {
  return vi.fn().mockImplementation(() => Promise.resolve(new Response('OK', { status: 200 })))
}

function makeEnv(assetsFetch = okFetch()) {
  return { ASSETS: { fetch: assetsFetch } }
}

function req(url: string, headers: Record<string, string> = {}) {
  // signal: null prevents AbortSignal propagation issues in Node test environment
  return new Request(url, { headers, signal: null })
}

describe('worker — http/www redirect', () => {
  it('redirects http → https', async () => {
    const res = await worker.fetch(req('http://wbgtcheck.com/'), makeEnv())
    expect(res.status).toBe(301)
    expect(res.headers.get('location')).toContain('https://')
  })

  it('redirects www → non-www', async () => {
    const res = await worker.fetch(req('https://www.wbgtcheck.com/'), makeEnv())
    expect(res.status).toBe(301)
    expect(res.headers.get('location')).not.toContain('www.')
  })

  it('combines www + trailing slash into single 301', async () => {
    const res = await worker.fetch(req('https://www.wbgtcheck.com/en/texas/'), makeEnv())
    expect(res.status).toBe(301)
    const location = res.headers.get('location')!
    expect(location).not.toContain('www.')
    expect(location).not.toMatch(/\/$/)
  })
})

describe('worker — trailing slash redirect', () => {
  it('strips trailing slash from non-root paths', async () => {
    const res = await worker.fetch(req('https://wbgtcheck.com/en/texas/'), makeEnv())
    expect(res.status).toBe(301)
    expect(res.headers.get('location')).toMatch(/\/en\/texas$/)
  })
})

describe('worker — bare path redirect', () => {
  it('redirects / to /es based on Accept-Language', async () => {
    const res = await worker.fetch(
      req('https://wbgtcheck.com/', { 'Accept-Language': 'es,en;q=0.9' }),
      makeEnv(),
    )
    expect(res.status).toBe(302)
    expect(res.headers.get('location')).toContain('/es')
  })

  it('redirects / to /en when Accept-Language is unsupported', async () => {
    const res = await worker.fetch(
      req('https://wbgtcheck.com/', { 'Accept-Language': 'xx' }),
      makeEnv(),
    )
    expect(res.status).toBe(302)
    expect(res.headers.get('location')).toContain('/en')
  })

  it('redirects /texas to /en/texas', async () => {
    const res = await worker.fetch(
      req('https://wbgtcheck.com/texas', { 'Accept-Language': 'en' }),
      makeEnv(),
    )
    expect(res.status).toBe(302)
    expect(res.headers.get('location')).toContain('/en/texas')
  })
})

describe('worker — lang-prefixed valid paths', () => {
  it('serves /en/texas via ASSETS', async () => {
    const assets = okFetch()
    await worker.fetch(req('https://wbgtcheck.com/en/texas'), makeEnv(assets))
    const fetchedUrl = new URL((assets.mock.calls[0]![0] as Request).url)
    expect(fetchedUrl.pathname).toBe('/en/texas')
  })

  it('serves /es/georgia via ASSETS', async () => {
    const assets = okFetch()
    await worker.fetch(req('https://wbgtcheck.com/es/georgia'), makeEnv(assets))
    const fetchedUrl = new URL((assets.mock.calls[0]![0] as Request).url)
    expect(fetchedUrl.pathname).toBe('/es/georgia')
  })
})

describe('worker — invalid paths return 404 + noindex', () => {
  it('returns 404 for /en/nonexistent-tool', async () => {
    const res = await worker.fetch(req('https://wbgtcheck.com/en/nonexistent-tool'), makeEnv())
    expect(res.status).toBe(404)
    expect(res.headers.get('X-Robots-Tag')).toBe('noindex')
  })

  it('returns 404 for /en/fake/deep/path', async () => {
    const res = await worker.fetch(req('https://wbgtcheck.com/en/fake/deep/path'), makeEnv())
    expect(res.status).toBe(404)
  })

  it('returns 404 for unsupported language prefix /fr/texas', async () => {
    const res = await worker.fetch(req('https://wbgtcheck.com/fr/texas'), makeEnv())
    expect(res.status).toBe(404)
  })
})

describe('worker — static files pass through', () => {
  it('passes /sitemap.xml directly to ASSETS', async () => {
    const assets = okFetch()
    await worker.fetch(req('https://wbgtcheck.com/sitemap.xml'), makeEnv(assets))
    const fetchedUrl = new URL((assets.mock.calls[0]![0] as Request).url)
    expect(fetchedUrl.pathname).toBe('/sitemap.xml')
  })

  it('does not lowercase hashed asset paths', async () => {
    const assets = okFetch()
    await worker.fetch(req('https://wbgtcheck.com/assets/index-3K27U7vi.js'), makeEnv(assets))
    const fetchedUrl = new URL((assets.mock.calls[0]![0] as Request).url)
    expect(fetchedUrl.pathname).toBe('/assets/index-3K27U7vi.js')
  })
})

describe('worker — /api/wbgt NWS proxy', () => {
  afterEach(() => {
    vi.unstubAllGlobals()
  })

  const pointsResponse = {
    properties: {
      forecastGridData: 'https://api.weather.gov/gridpoints/EWX/155,90',
      timeZone: 'America/Chicago',
      relativeLocation: { properties: { city: 'Austin', state: 'TX' } },
    },
  }

  const gridResponse = {
    properties: {
      wetBulbGlobeTemperature: {
        uom: 'wmoUnit:degC',
        values: [{ validTime: '2026-08-10T12:00:00+00:00/PT1H', value: 30 }],
      },
      temperature: {
        uom: 'wmoUnit:degC',
        values: [{ validTime: '2026-08-10T12:00:00+00:00/PT1H', value: 36 }],
      },
      relativeHumidity: {
        uom: 'wmoUnit:percent',
        values: [{ validTime: '2026-08-10T12:00:00+00:00/PT1H', value: 45 }],
      },
      windSpeed: {
        uom: 'wmoUnit:km_h-1',
        values: [{ validTime: '2026-08-10T12:00:00+00:00/PT1H', value: 15 }],
      },
      skyCover: {
        uom: 'wmoUnit:percent',
        values: [{ validTime: '2026-08-10T12:00:00+00:00/PT1H', value: 20 }],
      },
      irrelevantLayer: { uom: 'x', values: [{ validTime: 't/PT1H', value: 1 }] },
    },
  }

  function stubNws() {
    const fetchMock = vi.fn().mockImplementation((input: string | URL) => {
      const u = String(input)
      if (u.startsWith('https://api.weather.gov/points/')) {
        return Promise.resolve(new Response(JSON.stringify(pointsResponse), { status: 200 }))
      }
      if (u.startsWith('https://api.weather.gov/gridpoints/')) {
        return Promise.resolve(new Response(JSON.stringify(gridResponse), { status: 200 }))
      }
      return Promise.resolve(new Response('not found', { status: 404 }))
    })
    vi.stubGlobal('fetch', fetchMock)
    return fetchMock
  }

  it('400s on missing or non-numeric coordinates', async () => {
    const res = await worker.fetch(req('https://wbgtcheck.com/api/wbgt'), makeEnv())
    expect(res.status).toBe(400)
    const res2 = await worker.fetch(req('https://wbgtcheck.com/api/wbgt?lat=abc&lon=1'), makeEnv())
    expect(res2.status).toBe(400)
  })

  it('400s on out-of-range coordinates', async () => {
    const res = await worker.fetch(
      req('https://wbgtcheck.com/api/wbgt?lat=85&lon=-97'),
      makeEnv(),
    )
    expect(res.status).toBe(400)
  })

  it('proxies points→gridpoint and returns the slim payload with edge caching headers', async () => {
    const fetchMock = stubNws()
    const res = await worker.fetch(
      req('https://wbgtcheck.com/api/wbgt?lat=30.2672&lon=-97.7431'),
      makeEnv(),
    )
    expect(res.status).toBe(200)
    expect(res.headers.get('cache-control')).toBe('public, max-age=600')
    const body = (await res.json()) as Record<string, unknown>
    expect(body.hasWbgt).toBe(true)
    expect(body.location).toMatchObject({ city: 'Austin', state: 'TX', timeZone: 'America/Chicago' })
    expect(body).toHaveProperty('temperature')
    expect(body).toHaveProperty('skyCover')
    // Slimming: layers we don't use must not pass through
    expect(body).not.toHaveProperty('irrelevantLayer')
    // Coordinates rounded to 2 decimals before hitting NWS
    expect(String(fetchMock.mock.calls[0][0])).toContain('/points/30.27,-97.74')
  })

  it('sends the identifying User-Agent NWS requires', async () => {
    const fetchMock = stubNws()
    await worker.fetch(req('https://wbgtcheck.com/api/wbgt?lat=30.27&lon=-97.74'), makeEnv())
    expect(fetchMock.mock.calls.length).toBeGreaterThan(0)
    for (const call of fetchMock.mock.calls) {
      const init = call[1] as { headers: Record<string, string> }
      expect(init.headers['User-Agent']).toContain('wbgtcheck.com')
    }
  })

  it('reports hasWbgt=false when the office grid has no WBGT layer (EWX case)', async () => {
    const noWbgt = {
      properties: { ...gridResponse.properties, wetBulbGlobeTemperature: undefined },
    }
    vi.stubGlobal(
      'fetch',
      vi.fn().mockImplementation((input: string | URL) => {
        const u = String(input)
        if (u.includes('/points/')) {
          return Promise.resolve(new Response(JSON.stringify(pointsResponse), { status: 200 }))
        }
        return Promise.resolve(new Response(JSON.stringify(noWbgt), { status: 200 }))
      }),
    )
    const res = await worker.fetch(
      req('https://wbgtcheck.com/api/wbgt?lat=30.27&lon=-97.74'),
      makeEnv(),
    )
    const body = (await res.json()) as { hasWbgt: boolean }
    expect(body.hasWbgt).toBe(false)
  })

  it('502s (no-store) when NWS is down', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue(new Response('upstream error', { status: 500 })),
    )
    const res = await worker.fetch(
      req('https://wbgtcheck.com/api/wbgt?lat=30.27&lon=-97.74'),
      makeEnv(),
    )
    expect(res.status).toBe(502)
    expect(res.headers.get('cache-control')).toBe('no-store')
  })
})
